In [13]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline 
plt.rcParams['figure.figsize'] = [15, 5]

import warnings
warnings.filterwarnings('ignore')

In [14]:
%load_ext autoreload
%autoreload 2
%run '../../main.py'


from lib.helper import Functions
from lib.store.influxstore import InfluxStore

In [15]:
dataSetOps = DataSetOps()

dataSetOps.import_tick_data_set('/media/taleh/TIsStorage/archive/finance-data/currency/Tick/DAT_ASCII_EURUSD_T_201902.csv')

df = dataSetOps.df

In [76]:
from lib.engine.btengine import BackTestEngine
from lib.strategy.simple import SimpleStrategy
from lib.algorithm.randoma import RandomAlgorithm
from lib.algorithm.Amp1Algorithm import Amp1Algorithm

snnAlgo1 = Amp1Algorithm(10, 70)
strategy1 = SimpleStrategy()
btengine1 = BackTestEngine()
btengine1.init(df.head(50000), snnAlgo1, strategy1)

btengine1.run()

btengine1.report()

tick processed  2019-02-01 02:44:47.970000 10000 20.0 % 0 0
tick processed  2019-02-01 03:56:49.310000 20000 40.0 % 0 0
tick processed  2019-02-01 04:48:12.871000 30000 60.0 % 0 0
tick processed  2019-02-01 05:58:35.857000 40000 80.0 % 0 0
tick processed  2019-02-01 07:14:57.988000 50000 100.0 % 0 0
balance:  0
won count:  0
lost count:  0

In [81]:
snnAlgo1.data

         amp     close       max       min                time
0   0.000300  1.144135  1.144130  1.143995 2019-02-01 00:20:00
1   0.000130  1.144095  1.144145  1.144000 2019-02-01 00:30:00
2   0.000385  1.143775  1.144095  1.143760 2019-02-01 00:40:00
3   0.000640  1.143810  1.143825  1.143455 2019-02-01 00:50:00
4   0.000380  1.143680  1.143825  1.143445 2019-02-01 01:00:00
5   0.000300  1.143645  1.143815  1.143525 2019-02-01 01:10:00
6   0.000325  1.143820  1.143825  1.143490 2019-02-01 01:20:00
7   0.000045  1.143965  1.144045  1.143780 2019-02-01 01:30:00
8   0.000175  1.144000  1.144120  1.143870 2019-02-01 01:40:00
9   0.000260  1.143945  1.144040  1.143860 2019-02-01 01:50:00
10  0.000095  1.144210  1.144390  1.143945 2019-02-01 02:00:00
11  0.000375  1.144430  1.144610  1.144015 2019-02-01 02:10:00
12  0.000365  1.144400  1.144795  1.144245 2019-02-01 02:20:00
13  0.000705  1.144195  1.144475  1.144090 2019-02-01 02:30:00
14  0.000415  1.144075  1.144360  1.144060 2019-02-01 02:40:00
15  0.000305  1.144290  1.144600  1.144055 2019-02-01 02:50:00
16  0.000315  1.144770  1.144875  1.144285 2019-02-01 03:00:00
17  0.000620  1.144775  1.145015  1.144255 2019-02-01 03:10:00
18  0.000390  1.144670  1.145115  1.144625 2019-02-01 03:20:00
19  0.000450  1.144850  1.145075  1.144665 2019-02-01 03:30:00
20  0.000405  1.144825  1.145225  1.144670 2019-02-01 03:40:00
21  0.000600  1.144920  1.145030  1.144625 2019-02-01 03:50:00
22  0.000575  1.144840  1.144960  1.144455 2019-02-01 04:00:00
23  0.000385  1.144690  1.145025  1.144575 2019-02-01 04:10:00
24  0.000475  1.145395  1.145590  1.144550 2019-02-01 04:20:00
25  0.000200  1.146060  1.146385  1.145390 2019-02-01 04:30:00
26  0.000650  1.146360  1.146445  1.145735 2019-02-01 04:40:00
27  0.000450  1.146595  1.146635  1.145995 2019-02-01 04:50:00
28  0.000205  1.146665  1.146765  1.146430 2019-02-01 05:00:00
29  0.000170  1.146880  1.147180  1.146595 2019-02-01 05:10:00
30  0.000465  1.146925  1.147280  1.146715 2019-02-01 05:20:00
31  0.000540  1.146900  1.146935  1.146740 2019-02-01 05:30:00
32  0.000270  1.146675  1.146935  1.146665 2019-02-01 05:40:00
33  0.000315  1.146925  1.146950  1.146620 2019-02-01 05:50:00
34  0.000395  1.146735  1.146960  1.146555 2019-02-01 06:00:00
35  0.000345  1.146715  1.146905  1.146615 2019-02-01 06:10:00
36  0.000375  1.146950  1.146950  1.146530 2019-02-01 06:20:00
37  0.000045  1.147230  1.147395  1.146905 2019-02-01 06:30:00
38  0.000280  1.147430  1.147465  1.147115 2019-02-01 06:40:00
39  0.000330  1.147375  1.147480  1.147135 2019-02-01 06:50:00
40  0.000630  1.146975  1.147380  1.146850 2019-02-01 07:00:00
41  0.000785  1.146770  1.147020  1.146595 2019-02-01 07:10:00
42       NaN       NaN       NaN       NaN                 NaT
43       NaN       NaN       NaN       NaN                 NaT

In [11]:
import time

In [50]:
1548979200000000

1548979200000000

In [63]:
len(df)

2736589