In [3]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline 
plt.rcParams['figure.figsize'] = [15, 5]

In [4]:
%load_ext autoreload
%autoreload 2
%run '../../main.py'


from lib.helper import Functions
from lib.store.influxstore import InfluxStore

In [5]:
dataSetOps = DataSetOps()

dataSetOps.import_years(2018, 2018)
dataSetOps.prepareMin()

df = dataSetOps.df

df['price'] = df['price']

In [6]:
Functions.calc_integral(df)

In [13]:
def integral(arr):
    elem = arr[0]
    pSum = 0
    nSum = 0
    for a in arr:
        diff = a - elem
        if diff > 0:
            pSum = pSum + diff
        else:
            nSum = nSum - diff
    return pSum + nSum

df['intg'] = df['price'].shift(-9).rolling(window=10).apply(integral, raw=True)
df['intg2'] = df['price'].rolling(window=10).sum() - df['price'] * 10


df.dropna(inplace=True)

In [14]:
df

                      time    price     intg    intg2
27     2018-01-01 17:29:00  1.20065  0.00333 -0.00153
28     2018-01-01 17:30:00  1.20077  0.00298 -0.00246
29     2018-01-01 17:31:00  1.20070  0.00409 -0.00151
30     2018-01-01 17:32:00  1.20087  0.00327 -0.00279
31     2018-01-01 17:33:00  1.20076  0.00460 -0.00148
32     2018-01-01 17:34:00  1.20086  0.00420 -0.00210
33     2018-01-01 17:35:00  1.20129  0.00040 -0.00556
34     2018-01-01 17:36:00  1.20133  0.00018 -0.00514
35     2018-01-01 17:37:00  1.20131  0.00031 -0.00414
36     2018-01-01 17:38:00  1.20129  0.00060 -0.00307
37     2018-01-01 17:39:00  1.20134  0.00029 -0.00288
38     2018-01-01 17:40:00  1.20134  0.00029 -0.00231
39     2018-01-01 17:41:00  1.20134  0.00032 -0.00167
40     2018-01-01 17:42:00  1.20134  0.00035 -0.00120
41     2018-01-01 17:43:00  1.20136  0.00030 -0.00080
42     2018-01-01 17:44:00  1.20136  0.00031 -0.00030
43     2018-01-01 17:45:00  1.20135  0.00036 -0.00014
44     2018-01-01 17:46:00  1.20134  0.00044 -0.00003
45     2018-01-01 17:47:00  1.20144  0.00059 -0.00090
46     2018-01-01 17:48:00  1.20148  0.00096 -0.00111
47     2018-01-01 17:49:00  1.20134  0.00037  0.00029
48     2018-01-01 17:50:00  1.20137  0.00017  0.00002
49     2018-01-01 17:51:00  1.20137  0.00037  0.00005
50     2018-01-01 17:52:00  1.20133  0.00137  0.00044
51     2018-01-01 17:53:00  1.20137  0.00208  0.00005
52     2018-01-01 17:54:00  1.20139  0.00274 -0.00012
53     2018-01-01 17:55:00  1.20139  0.00340 -0.00008
54     2018-01-01 17:56:00  1.20141  0.00396 -0.00021
55     2018-01-01 17:57:00  1.20139  0.00434 -0.00006
56     2018-01-01 17:58:00  1.20139  0.00482 -0.00015
...                    ...      ...      ...      ...
372549 2018-12-31 16:03:00  1.14571  0.00044  0.00049
372550 2018-12-31 16:04:00  1.14571  0.00057  0.00023
372551 2018-12-31 16:05:00  1.14574  0.00048 -0.00023
372552 2018-12-31 16:06:00  1.14573  0.00070 -0.00026
372553 2018-12-31 16:07:00  1.14571  0.00105 -0.00021
372554 2018-12-31 16:08:00  1.14575  0.00084 -0.00057
372555 2018-12-31 16:09:00  1.14575  0.00091 -0.00043
372556 2018-12-31 16:10:00  1.14582  0.00034 -0.00092
372557 2018-12-31 16:11:00  1.14581  0.00048 -0.00067
372558 2018-12-31 16:12:00  1.14581  0.00068 -0.00056
372559 2018-12-31 16:13:00  1.14584  0.00067 -0.00073
372560 2018-12-31 16:14:00  1.14584  0.00083 -0.00060
372561 2018-12-31 16:15:00  1.14590  0.00062 -0.00104
372562 2018-12-31 16:16:00  1.14592  0.00063 -0.00105
372563 2018-12-31 16:17:00  1.14590  0.00080 -0.00066
372564 2018-12-31 16:18:00  1.14582  0.00137  0.00021
372565 2018-12-31 16:19:00  1.14580  0.00172  0.00046
372566 2018-12-31 16:20:00  1.14592  0.00094 -0.00064
372567 2018-12-31 16:21:00  1.14601  0.00063 -0.00134
372568 2018-12-31 16:22:00  1.14600  0.00120 -0.00105
372569 2018-12-31 16:23:00  1.14600  0.00160 -0.00089
372570 2018-12-31 16:24:00  1.14599  0.00211 -0.00064
372571 2018-12-31 16:25:00  1.14599  0.00263 -0.00055
372572 2018-12-31 16:26:00  1.14601  0.00303 -0.00066
372573 2018-12-31 16:27:00  1.14599  0.00352 -0.00037
372574 2018-12-31 16:28:00  1.14601  0.00365 -0.00038
372575 2018-12-31 16:29:00  1.14622  0.00181 -0.00206
372576 2018-12-31 16:30:00  1.14635  0.00091 -0.00293
372577 2018-12-31 16:31:00  1.14658  0.00179 -0.00466
372578 2018-12-31 16:32:00  1.14640  0.00100 -0.00246

[372552 rows x 4 columns]

In [16]:
size = 1000
# df[['price']].head(size).plot()
# df[['intg']].head(size).plot()
store = InfluxStore()
store.storeDf(df[['time', 'intg', 'intg2']], 'class-feature-detector-1', 3)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000